version: '3.8'

services:
  ai-lab:
    build: .
    image: my-tiny-llama-lab
    ports:
      - "8888:8888"
    volumes:
      # 현재 폴더(.) 전체를 컨테이너의 /workspace 로 연결합니다.
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]